name: channels.json'dan m3u oluştur

on:
  push:
    paths:
      - 'm3u-editor/channels.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Reponun klonlanması
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Gerekli paketleri kur
        run: pip install --upgrade pip

      - name: JSON'u M3U'ya çevir
        run: python json2m3u.py

      - name: Değişiklikleri commit et ve pushla
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GokhanBot"
          git config user.email "iptv-bot@gokhanelgul.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add gkhn190744.m3u
          git commit -m "Editörden güncellenen m3u dosyası" || echo "Değişiklik yok"
          git push
